DEFAULT:
  multiline_template: |
    {{#unit}}{{{unit}}}{{/unit}}
    {{#house_name}}{{{house_name}}}{{/house_name}}
    {{{street_number}}} {{{street_name}}}
    {{#locality}}{{{locality}}}{{/locality}}
    {{{city}}}
    {{{postalcode}}}
    {{#state}}{{{state}}}{{/state}}
    {{#country}}{{{country}}}{{/country}}
  singleline_template: >
    {{#unit}}{{{unit}}},{{/unit}}
    {{#house_name}}{{{house_name}}},{{/house_name}}
    {{{street_number}}} {{{street_name}}},
    {{#locality}}{{{locality}}},{{/locality}}
    {{{city}}},
    {{{postalcode}}}{{#state}}, {{{state}}}{{/state}}, {{#country}}{{{country}}}{{/country}}